name: Central CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
    #   - name: Setup Node.js (if using JavaScript)
    #     uses: actions/setup-node@v3
    #     with:
    #       node-version: '16'

      - name: Run Hello World
        run: echo "Hello World from centralized workflow"
