name: workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: InfraConfig
      uses: AlejandroJimenezGutierrez/HackatonActionMaster/InfraConfig@main

    - name: Build
      run: echo "Building"

    - name: Deploy
      run: echo "Deploying"

    - name: Test
      uses: AlejandroJimenezGutierrez/HackatonActionMaster/Test@main
      with:
        param1: "valor1"
        param2: "valor2"
